### ISSUE TITLE
command line options

### ISSUE THREAD

**Issue by zionbutbika** [JonasDralle/InstallDirChanger#9]
Hi Joans,

does it have any command line switches?
this way it can be used during a script in unattended mode

thanks
zion

**Comment by JonasDralle** [comment]
great Idea! It's not supported at the moment but I'll add it in the next version

please dont keep your hopes up too high because I'm currently busy learnign for my final exams

Thank you for letting me know :+1:

**Comment by zionbutbika** [comment]
No problem
Good luck with your exams
בתאריך 12 באפר׳ 2016 09:28,‏ "Jonas Dralle" <notifications@github.com> כתב:

**Comment by JonasDralle** [comment]
It's my computer science exam anyway so I added your feature request. :smiley: 

It's not available as an official version yet but I compiled you a pre-build version that has this new feature included. [**You can download it here**](https://app.box.com/s/74b5tlnl67c810kaef38z2ygrh5rdxvy). I compiled it just for you.

You can compile directly from source [here](https://github.com/JonasDralle/InstallDirChanger/tree/develop) if you like to.

	Usage: Install Dir Changer.exe [OPTION] [...]

	Options:
	   -?, --help                     Displays help and exits 
	   -a STRING, --change32=STRING   Change the registry value of the 32-bit 
									  default installation path 
	   -b STRING, --change64=STRING   Change the registry value of the 64-bit 
									  default installation path 
	   -q, --quiet                    Starts the software without user interface. 
									  Software will quit when all arg-specified 
									  commands are executed. This is helpful for 
									  servers and scripts. 
	   --version                      Print version and exits 

Please note that this is a pre-build version. Some details might be diffrent in the 1.3 version.

Have a good day

**Comment by JonasDralle** [comment]
I added your name under contributer in the [Readme-file](https://github.com/JonasDralle/InstallDirChanger/blob/d7b17f0d9af96e934907dc7e972a82411ae6bce0/README.md)
